services:
    nginx:
        image: nginx:1.27.2-alpine
        ports:
            - "${HTTP_PORT:-80}:80"
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
            - .:/var/www/html

    php:
        build:
            context: docker/php
            args:
                USER_ID: ${USER_ID}
                GROUP_ID: ${GROUP_ID}
        volumes:
            - ./:/var/www/html
            - ./docker/php/config/ext/${XDEBUG_ENABLE}-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./docker/php/config/php.ini:/usr/local/etc/php/php.ini
        environment:
            PHP_IDE_CONFIG: "serverName=hslibs-panel"

    mysql:
        image: mysql:9.1.0
        ports:
            - '${MYSQL_PORT:-3308}:3306'
        volumes:
            - ./var/data/mysqldb:/var/lib/mysql
        environment:
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}

    redis:
        image: redis:7.0.0-alpine
        ports:
            - "${REDIS_PORT:-6379}:6379"

    nodejs:
        image: node:22.9.0-alpine
        user: "${USER_ID}:${GROUP_ID}"
        volumes:
            - ./:/var/www/html
        working_dir: /var/www/html
        command: ["npm", "run", "dev"]
